import crypto from 'node:crypto';

const region='auto';const service='s3';
function config(){const accountId=process.env.R2_ACCOUNT_ID;const accessKeyId=process.env.R2_ACCESS_KEY_ID;const secretAccessKey=process.env.R2_SECRET_ACCESS_KEY;const bucket=process.env.R2_BUCKET_NAME||'milni-media';if(!accountId||!accessKeyId||!secretAccessKey)throw new Error('R2 is not configured');return{accountId,accessKeyId,secretAccessKey,bucket,host:`${accountId}.r2.cloudflarestorage.com`}}
const hash=(value:string|Buffer|Uint8Array)=>crypto.createHash('sha256').update(value).digest('hex');const hmac=(key:Buffer|string,value:string)=>crypto.createHmac('sha256',key).update(value).digest();
function encodePath(path:string){return path.split('/').map(encodeURIComponent).join('/')}
function signedHeaders(method:string,key:string,payloadHash:string,contentType?:string){const {accessKeyId,secretAccessKey,bucket,host}=config();const now=new Date();const amzDate=now.toISOString().replace(/[:-]|\.\d{3}/g,'');const date=amzDate.slice(0,8);const uri=`/${bucket}/${encodePath(key)}`;const headers:Record<string,string>={'host':host,'x-amz-content-sha256':payloadHash,'x-amz-date':amzDate};if(contentType)headers['content-type']=contentType;const names=Object.keys(headers).sort();const canonicalHeaders=names.map(name=>`${name}:${headers[name].trim()}\n`).join('');const signed=names.join(';');const canonical=[method,uri,'',canonicalHeaders,signed,payloadHash].join('\n');const scope=`${date}/${region}/${service}/aws4_request`;const toSign=`AWS4-HMAC-SHA256\n${amzDate}\n${scope}\n${hash(canonical)}`;const kDate=hmac(`AWS4${secretAccessKey}`,date);const kRegion=hmac(kDate,region);const kService=hmac(kRegion,service);const kSigning=hmac(kService,'aws4_request');const signature=crypto.createHmac('sha256',kSigning).update(toSign).digest('hex');return{url:`https://${host}${uri}`,headers:{...headers,Authorization:`AWS4-HMAC-SHA256 Credential=${accessKeyId}/${scope}, SignedHeaders=${signed}, Signature=${signature}`}}}
export async function putObject(key:string,body:Buffer,contentType:string){const signed=signedHeaders('PUT',key,hash(body),contentType);const uploadBody=new Uint8Array(body);const response=await fetch(signed.url,{method:'PUT',headers:signed.headers,body:uploadBody});if(!response.ok)throw new Error(`R2 upload failed: ${response.status} ${await response.text()}`)}
export async function getObject(key:string){const signed=signedHeaders('GET',key,hash(''));return fetch(signed.url,{headers:signed.headers})}
export async function deleteObject(key:string){const signed=signedHeaders('DELETE',key,hash(''));const response=await fetch(signed.url,{method:'DELETE',headers:signed.headers});if(!response.ok&&response.status!==404)throw new Error(`R2 delete failed: ${response.status}`)}
export function safeObjectKey(value:string){return value.toLowerCase().replace(/[^a-z0-9._/-]+/g,'-').replace(/\.{2,}/g,'.').replace(/^\/+|\/+$/g,'')}
