import crypto from 'node:crypto';
import {NextResponse} from 'next/server';
import {d1Execute,d1Query} from '../../../../../../lib/d1';
import {currentGuestSession} from '../../../../../../lib/guestSession';
import {publishWeddingNotification} from '../../../../../../lib/notifications';
type MessageRow={id:string;sender_profile_id:string;body:string;gif_url:string|null;created_at:string};
async function ensureGifColumn(){try{await d1Execute('ALTER TABLE messages ADD COLUMN gif_url TEXT')}catch{}}
function safeGifUrl(value:unknown){const raw=String(value||'').trim();if(!raw)return null;try{const url=new URL(raw);return url.protocol==='https:'&&(url.hostname==='giphy.com'||url.hostname.endsWith('.giphy.com'))?url.toString():null}catch{return null}}
async function access(slug:string,matchId:string){const session=await currentGuestSession();const wedding=(await d1Query<{id:string}>('SELECT id FROM weddings WHERE slug=? LIMIT 1',[slug]))[0];if(!session||!wedding||session.weddingId!==wedding.id||session.weddingSlug!==slug)return null;const me=(await d1Query<{id:string;name:string}>('SELECT id,name FROM singles_profiles WHERE wedding_id=? AND guest_id=? AND opted_in=1 LIMIT 1',[wedding.id,session.guestId]))[0];if(!me)return null;const match=(await d1Query<{id:string;profile_one_id:string;profile_two_id:string}>('SELECT id,profile_one_id,profile_two_id FROM singles_matches WHERE id=? AND wedding_id=? AND (profile_one_id=? OR profile_two_id=?) LIMIT 1',[matchId,wedding.id,me.id,me.id]))[0];if(!match)return null;const otherId=match.profile_one_id===me.id?match.profile_two_id:match.profile_one_id;const other=(await d1Query<{name:string;guest_id:string;photo_object_key:string|null}>('SELECT name,guest_id,photo_object_key FROM singles_profiles WHERE id=? AND wedding_id=? LIMIT 1',[otherId,wedding.id]))[0];return{weddingId:wedding.id,meId:me.id,meName:me.name,otherId,otherGuestId:other?.guest_id,other,conversationId:'conversation-'+match.id}}
export async function GET(_request:Request,{params}:{params:Promise<{slug:string;matchId:string}>}){try{const{slug,matchId}=await params;const ctx=await access(slug,matchId);if(!ctx)return NextResponse.json({ok:false,error:'Conversation not available.'},{status:403});await ensureGifColumn();const rows=await d1Query<MessageRow>('SELECT id,sender_profile_id,body,gif_url,created_at FROM messages WHERE conversation_id=? ORDER BY created_at ASC',[ctx.conversationId]);return NextResponse.json({ok:true,meProfileId:ctx.meId,other:{profileId:ctx.otherId,name:ctx.other?.name??'Match',photoUrl:ctx.other?.photo_object_key?'/api/media?key='+encodeURIComponent(ctx.other.photo_object_key):undefined},messages:rows.map(row=>({id:row.id,senderProfileId:row.sender_profile_id,body:row.body==='\u200B'?'':row.body,gifUrl:row.gif_url,createdAt:row.created_at}))})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:'Could not load conversation.'},{status:500})}}
export async function POST(request:Request,{params}:{params:Promise<{slug:string;matchId:string}>}){try{const{slug,matchId}=await params;const ctx=await access(slug,matchId);if(!ctx)return NextResponse.json({ok:false,error:'Conversation not available.'},{status:403});const payload=await request.json() as {body?:string;gifUrl?:string};const text=String(payload.body??'').trim();const gifUrl=safeGifUrl(payload.gifUrl);if((!text&&!gifUrl)||text.length>2000)return NextResponse.json({ok:false,error:'Add a message or GIF (up to 2000 characters).'},{status:400});await ensureGifColumn();await d1Execute('INSERT OR IGNORE INTO conversations(id,wedding_id,match_id,created_at) VALUES(?,?,?,CURRENT_TIMESTAMP)',[ctx.conversationId,ctx.weddingId,matchId]);const id=crypto.randomUUID();const storedBody=text||'\u200B';await d1Execute('INSERT INTO messages(id,conversation_id,sender_profile_id,body,gif_url,created_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP)',[id,ctx.conversationId,ctx.meId,storedBody,gifUrl]);if(ctx.otherGuestId){try{await publishWeddingNotification({weddingId:ctx.weddingId,type:'singles_message',title:'New Singles message',message:(ctx.meName||'Your match')+' sent you a message.',url:'/wedding/'+encodeURIComponent(slug)+'/singles?match='+encodeURIComponent(matchId),sourceId:id,recipientGuestId:ctx.otherGuestId})}catch(notificationError){console.error('Singles message notification failed',notificationError)}}return NextResponse.json({ok:true,id})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:'Could not send message.'},{status:500})}}
