'use client';
import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import QRCode from 'qrcode';
import {invitationCode,WeddingDraft} from '../../../../lib/weddingDraft';
import styles from './page.module.scss';
type InviteGuest={id:string;name:string;group:string;hasToken:boolean;link:string|null};
export default function InvitationManager(){const params=useParams();const slug=String(params.slug||'');const[draft,setDraft]=useState<WeddingDraft|null>(null);const[guests,setGuests]=useState<InviteGuest[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState('');const[qr,setQr]=useState<Record<string,string>>({});
 const load=async()=>{setError('');const[w,g]=await Promise.all([fetch(`/api/weddings/${encodeURIComponent(slug)}`,{cache:'no-store'}),fetch(`/api/invitations/${encodeURIComponent(slug)}`,{cache:'no-store'})]);const wx=await w.json(),gx=await g.json();if(!g.ok)throw new Error(gx.error||'Organiser sign-in required.');if(wx.ok)setDraft(wx.draft);setGuests(gx.guests??[])};useEffect(()=>{load().catch(e=>setError(e.message))},[slug]);
 const ensure=async(guest:InviteGuest,regenerate=false)=>{setBusy(guest.id);setError('');try{const r=await fetch(`/api/invitations/${encodeURIComponent(slug)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({guestId:guest.id,regenerate})});const x=await r.json();if(!r.ok)throw new Error(x.error||'Could not create invitation.');setGuests(gs=>gs.map(g=>g.id===guest.id?{...g,hasToken:true,link:x.link}:g));return x.link as string}catch(e){setError(e instanceof Error?e.message:'Could not create invitation.');return null}finally{setBusy('')}};
 const copy=async(g:InviteGuest)=>{const link=g.link||await ensure(g);if(link)await navigator.clipboard.writeText(link)};
 const showQr=async(g:InviteGuest)=>{const link=g.link||await ensure(g);if(link)setQr(q=>({...q,[g.id]:q[g.id]||''})),QRCode.toDataURL(link,{width:700,margin:2,errorCorrectionLevel:'H'}).then(url=>setQr(q=>({...q,[g.id]:url})))};
 const code=draft?invitationCode(draft):'';return <section className={styles.manager}><div className={styles.managerHead}><div><small>INVITATION CENTRE</small><h2>Share & manage invitations</h2><p>Every guest can have a personal instant-access link and QR. The wedding code remains the fallback.</p></div><div className={styles.fallback}><span>Fallback code</span><strong>{code||'…'}</strong></div></div>{error&&<div className={styles.managerError}>{error}</div>}<div className={styles.guestInvites}>{guests.map(g=><article key={g.id}><div><strong>{g.name}</strong><small>{g.group||'Guest'}</small></div><div className={styles.inviteActions}><button onClick={()=>copy(g)} disabled={busy===g.id}>{g.hasToken?'Copy link':'Create link'}</button><button onClick={()=>showQr(g)} disabled={busy===g.id}>QR code</button>{g.hasToken&&<button className={styles.regenerate} onClick={()=>ensure(g,true)}>Regenerate</button>}</div>{qr[g.id]&&<div className={styles.personalQr}><img src={qr[g.id]} alt={`QR invitation for ${g.name}`}/><p>Scan for instant access. No camera? Use the personal link or <b>{code}</b> with their name on the MILNI home page.</p></div>}</article>)}</div></section>}