'use client';
import {ChangeEvent,useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {useParams} from 'next/navigation';
import WeddingSidebar from './WeddingSidebar';
import {WeddingDraft,emptyDraft,formatDateRange,readSharedWeddingDraft,readWeddingDraft} from '../../../lib/weddingDraft';
import dashboard from './dashboard.module.scss';
import styles from './moments.module.scss';

type Comment={id:string;post_id:string;author_id:string;author_name:string;author_role:string;message:string;media_url:string|null;created_at:string};
type Moment={id:string;author_id:string;author_name:string;author_role:string;message:string;media_url:string|null;event_id:string|null;event_name:string|null;created_at:string;like_count:number;comment_count:number;liked_by_me:boolean;comments:Comment[]};
const VIEW_MODE_KEY='milni:view-mode';

export default function MomentsPage(){
 const params=useParams();const slug=String(params.slug||'our-wedding');const base=`/wedding/${slug}`;
 const[draft,setDraft]=useState<WeddingDraft>(emptyDraft);const[posts,setPosts]=useState<Moment[]>([]);const[message,setMessage]=useState('');const[eventId,setEventId]=useState('');const[photo,setPhoto]=useState<File|null>(null);const[photoPreview,setPhotoPreview]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[canPost,setCanPost]=useState(false);const[actorId,setActorId]=useState('');const[organiser,setOrganiser]=useState(false);const[organiserAuthed,setOrganiserAuthed]=useState(false);const[modeReady,setModeReady]=useState(false);const[commentDrafts,setCommentDrafts]=useState<Record<string,string>>({});const[justLiked,setJustLiked]=useState<string>('');const[commentFiles,setCommentFiles]=useState<Record<string,File|null>>({});const inputRef=useRef<HTMLInputElement>(null);
 const events=useMemo(()=>(draft.schedule??[]).flatMap(day=>day.events.map(event=>({id:event.id,name:event.name,label:`${day.label} · ${event.name}`}))),[draft.schedule]);
 useEffect(()=>{const local=readWeddingDraft();void readSharedWeddingDraft(slug,local).then(setDraft).catch(()=>setDraft(local));void Promise.all([fetch('/api/organiser-session',{cache:'no-store'}).then(r=>r.json()),load()]).then(([o])=>{const authed=!!o.organiser;setOrganiserAuthed(authed);setOrganiser(authed&&localStorage.getItem(VIEW_MODE_KEY)==='organiser');setModeReady(true)}).catch(()=>setModeReady(true))},[slug]);
 async function load(){const r=await fetch(`/api/moments/${encodeURIComponent(slug)}`,{cache:'no-store'});const x=await r.json();if(!r.ok)throw new Error(x.error||'Could not load moments');setPosts(x.posts??[]);setCanPost(!!x.canPost);setActorId(x.actor?.id||'')}
 const setMode=(next:boolean)=>{if(next&&!organiserAuthed)return;setOrganiser(next);localStorage.setItem(VIEW_MODE_KEY,next?'organiser':'guest')};
 const upload=async(file:File,area:string)=>{const form=new FormData();form.append('file',file,file.name);form.append('wedding',slug);form.append('area','moments');form.append('album',area);const r=await fetch('/api/media/upload',{method:'POST',body:form});const x=await r.json();if(!r.ok)throw new Error(x.error||'Photo upload failed');return String(x.url)};
 const choosePhoto=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0]||null;setPhoto(file);if(photoPreview)URL.revokeObjectURL(photoPreview);setPhotoPreview(file?URL.createObjectURL(file):'')};
 const post=async()=>{if(!message.trim()&&!photo)return;setBusy(true);setError('');try{const mediaUrl=photo?await upload(photo,'posts'):'';const event=events.find(e=>e.id===eventId);const r=await fetch(`/api/moments/${encodeURIComponent(slug)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message,mediaUrl,eventId:event?.id,eventName:event?.name})});const x=await r.json();if(!r.ok)throw new Error(x.error||'Could not share moment');setPosts(p=>[x.post,...p]);setMessage('');setPhoto(null);if(photoPreview)URL.revokeObjectURL(photoPreview);setPhotoPreview('')}catch(e){setError(e instanceof Error?e.message:'Could not share moment')}finally{setBusy(false)}};
 const like=async(id:string)=>{const wasLiked=posts.find(x=>x.id===id)?.liked_by_me;if(!wasLiked){setJustLiked(id);window.setTimeout(()=>setJustLiked(v=>v===id?'':v),650)}setPosts(p=>p.map(x=>x.id===id?{...x,liked_by_me:!x.liked_by_me,like_count:Math.max(0,x.like_count+(x.liked_by_me?-1:1))}:x));const r=await fetch(`/api/moments/${encodeURIComponent(slug)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'like',postId:id})});if(!r.ok)void load()};
 const comment=async(postId:string)=>{const text=commentDrafts[postId]?.trim()||'';const file=commentFiles[postId];if(!text&&!file)return;try{const mediaUrl=file?await upload(file,'comments'):'';const r=await fetch(`/api/moments/${encodeURIComponent(slug)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'comment',postId,message:text,mediaUrl})});const x=await r.json();if(!r.ok)throw new Error(x.error||'Could not comment');setPosts(p=>p.map(post=>post.id===postId?{...post,comments:[...post.comments,x.comment],comment_count:post.comment_count+1}:post));setCommentDrafts(v=>({...v,[postId]:''}));setCommentFiles(v=>({...v,[postId]:null}))}catch(e){setError(e instanceof Error?e.message:'Could not comment')}};
 const remove=async(id:string,type='post')=>{if(!window.confirm(type==='comment'?'Remove this comment?':'Remove this moment?'))return;const r=await fetch(`/api/moments/${encodeURIComponent(slug)}`,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id,type})});if(r.ok)void load()};
 const names=[draft.partnerOne,draft.partnerTwo].filter(Boolean).join(' & ')||'Our Wedding';
 return <main className={dashboard.shell}><WeddingSidebar base={base} active="moments" showOrganiser={modeReady} organiser={organiser} onToggleOrganiser={()=>setMode(!organiser)}/><section className={dashboard.content}>{modeReady&&organiser&&<div className={dashboard.organiserBar}><strong>Organiser mode</strong><span>You can moderate any Moment or comment.</span><button onClick={()=>setMode(false)}>Preview as guest</button></div>}<header className={dashboard.pageHero}><div><small>{names.toUpperCase()}</small><h1>Moments</h1><p>{formatDateRange(draft.startDate,draft.endDate)} · The wedding, as everyone saw it.</p></div><Link href={base}>← Wedding home</Link></header><div className={styles.wrap}>
 {canPost?<section className={styles.composer}><div className={styles.composerTop}><div className={styles.avatar}>♡</div><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Share a moment with everyone…"/>{photoPreview&&<div className={styles.preview}><img src={photoPreview} alt="Selected"/><button onClick={()=>{setPhoto(null);setPhotoPreview('')}}>×</button></div>}</div><div className={styles.composerActions}><div><button className={styles.photoButton} onClick={()=>inputRef.current?.click()}>▧ Photo</button><input ref={inputRef} hidden type="file" accept="image/*" onChange={choosePhoto}/><select value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">Whole wedding</option>{events.map(e=><option key={e.id} value={e.id}>{e.label}</option>)}</select></div><button disabled={busy||(!message.trim()&&!photo)} onClick={post}>{busy?'Sharing…':'Share moment'}</button></div></section>:<section className={styles.joinNote}>Join this wedding from your invitation to share, like and comment.</section>}
 {error&&<p className={styles.error}>{error}</p>}
 <div className={styles.feedIntro}><span>{posts.length} moment{posts.length===1?'':'s'} shared</span><Link href={`${base}/photos`}>Browse wedding photos →</Link></div><section className={styles.feed}>{posts.length?posts.map(post=><article id={`moment-${post.id}`} className={`${styles.post} ${justLiked===post.id?styles.likePop:''}`} key={post.id}><header><div className={styles.avatar}>{post.author_name.slice(0,1).toUpperCase()}</div><div><strong>{post.author_name}</strong>{post.author_role==='organiser'&&<b>ORGANISER</b>}<span>{timeAgo(post.created_at)}{post.event_name?` · ${post.event_name}`:''}</span></div>{(organiser||post.author_id===actorId)&&<button className={styles.more} onClick={()=>remove(post.id)}>×</button>}</header>{post.message&&<p className={styles.message}>{post.message}</p>}{post.media_url&&<img className={styles.postPhoto} src={post.media_url} alt="Wedding moment"/>}<div className={styles.counts}><span>{post.like_count? `♥ ${post.like_count}`:''}</span><span>{post.comment_count?`${post.comment_count} comment${post.comment_count===1?'':'s'}`:''}</span></div><div className={styles.reactions}><button className={post.liked_by_me?styles.liked:''} disabled={!canPost} onClick={()=>like(post.id)}>{post.liked_by_me?'♥':'♡'} {post.liked_by_me?'Liked':'Like'}</button><button onClick={()=>document.getElementById(`comment-${post.id}`)?.focus()}>◇ Comment</button><label>▧ Photo<input type="file" accept="image/*" onChange={e=>setCommentFiles(v=>({...v,[post.id]:e.target.files?.[0]||null}))}/></label></div>{post.comments.length>0&&<div className={styles.comments}>{post.comments.map(c=><div className={styles.comment} key={c.id}><div className={styles.miniAvatar}>{c.author_name.slice(0,1).toUpperCase()}</div><div><div className={styles.commentBubble}><strong>{c.author_name}{c.author_role==='organiser'&&<b> ORGANISER</b>}</strong>{c.message&&<p>{c.message}</p>}{c.media_url&&<img src={c.media_url} alt="Comment attachment"/>}</div><span>{timeAgo(c.created_at)}</span></div>{(organiser||c.author_id===actorId)&&<button onClick={()=>remove(c.id,'comment')}>×</button>}</div>)}</div>}{canPost&&<div className={styles.commentComposer}><div className={styles.miniAvatar}>♡</div><input id={`comment-${post.id}`} value={commentDrafts[post.id]||''} onChange={e=>setCommentDrafts(v=>({...v,[post.id]:e.target.value}))} onKeyDown={e=>{if(e.key==='Enter')void comment(post.id)}} placeholder={commentFiles[post.id]?'Add a caption to your photo…':'Write a comment…'}/><button onClick={()=>comment(post.id)}>{commentFiles[post.id]?'▧ +':'→'}</button></div>}</article>):<div className={styles.empty}><b>♡</b><h2>The first Moment is waiting.</h2><p>Share a photo, a message, or something everyone will still be laughing about tomorrow.</p></div>}</section>
 </div></section></main>
}
function timeAgo(value:string){const ms=Date.now()-new Date(value).getTime();const mins=Math.max(0,Math.floor(ms/60000));if(mins<1)return'Just now';if(mins<60)return`${mins}m`;const hours=Math.floor(mins/60);if(hours<24)return`${hours}h`;const days=Math.floor(hours/24);if(days<7)return`${days}d`;return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short'}).format(new Date(value))}
