'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { WeddingDraft, emptyDraft, formatDateRange, readWeddingDraft, writeWeddingDraft, Guest, SongRequest } from '../../../lib/weddingDraft';
import styles from './dashboard.module.scss';

type Section='home'|'schedule'|'events'|'travel'|'menu'|'music'|'photos'|'guests'|'singles'|'live';
const nav:[Section,string,string][]=[['home','⌂','Home'],['schedule','▣','Schedule'],['events','✦','Events'],['travel','▤','Travel'],['menu','♨','Menu'],['music','♫','Music'],['photos','▧','Photos'],['guests','♧','Guests'],['singles','♡','Singles'],['live','♢','Live']];
const samples={travel:[['Coach to the Gurdwara','09:00','Hotel entrance','Seats reserved for wedding guests'],['Coach to reception','15:30','Gurdwara car park','Departs after photographs'],['Return coaches','00:00 & 01:30','Reception entrance','Two late-night departures']],menu:[['Welcome dinner','Vegetarian sharing feast','Paneer tikka · samosas · chaat · dal makhani'],['Wedding breakfast','Punjabi & British menu','All dietary requirements catered for'],['Late-night food','Midnight snacks','Chai · masala fries · sweet treats']]};
const starterGuests:Guest[]=[['Aman Kapoor','Groom’s family','Going'],['Priya Shah','Bride’s family','Going'],['Jas Singh','Friends','Going'],['Meera Patel','Friends','Awaiting RSVP'],['Ravi & Neha','Family','Going']].map((g,i)=>({id:`guest-${i}`,name:g[0],group:g[1],status:g[2] as Guest['status']}));
const starterSongs:SongRequest[]=['Mundian To Bach Ke · Panjabi MC','Nachde Ne Saare · Jasleen Royal','This Will Be · Natalie Cole'].map((song,i)=>({id:`song-${i}`,song,likes:12-i*3}));
export default function WeddingDashboard({section='home'}:{section?:Section}){
 const [draft,setDraft]=useState<WeddingDraft>(emptyDraft); const [organiser,setOrganiser]=useState(false); const params=useParams();
 useEffect(()=>setDraft(readWeddingDraft()),[]);
 const save=(patch:Partial<WeddingDraft>)=>{const next={...draft,...patch};setDraft(next);writeWeddingDraft(patch)};
 const slug=String(params.slug||'our-wedding'); const base=`/wedding/${slug}`; const names=[draft.partnerOne,draft.partnerTwo].filter(Boolean).join(' & ')||'Our Wedding';
 const events=useMemo(()=>draft.schedule?.flatMap(day=>day.events.map(e=>({...e,day:day.date,label:day.label})))??[],[draft.schedule]);
 const pageTitle={home:'Welcome',schedule:'Wedding schedule',events:'Events',travel:'Travel & coaches',menu:'Menus',music:'Song requests',photos:'Wedding photos',guests:'Guest list',singles:'Singles',live:'Live updates'}[section];
 return <main className={styles.shell}><aside className={styles.sidebar}><Link href={base} className={styles.logo}>MILNI<small>PEOPLE · TRADITIONS · TOGETHER</small></Link><nav>{nav.map(([key,icon,label])=><Link key={key} className={section===key?styles.active:''} href={key==='home'?base:`${base}/${key}`}>{icon}<span>{label}</span></Link>)}</nav><button className={styles.organiserToggle} onClick={()=>setOrganiser(v=>!v)}>{organiser?'✓ Organiser mode':'⚙ Organiser mode'}</button><div className={styles.sideQuote}>Good<br/>People<br/>Great<br/>Celebrations</div></aside><section className={styles.content}>
 {organiser&&<div className={styles.organiserBar}><strong>Organiser mode</strong><span>You’re editing the wedding. Changes on this prototype are saved in this browser.</span><button onClick={()=>setOrganiser(false)}>Preview as guest</button></div>}
 {section==='home'?<Home draft={draft} names={names} base={base} events={events}/>:<><header className={styles.pageHero}><div><small>{names.toUpperCase()}</small><h1>{pageTitle}</h1><p>{formatDateRange(draft.startDate,draft.endDate)} · {draft.city||'Location to be confirmed'}</p></div><Link href={base}>← Wedding home</Link></header><div className={styles.pageBody}>{section==='schedule'&&<Schedule draft={draft}/>} {section==='events'&&<Events events={events}/>} {section==='travel'&&<Travel/>} {section==='menu'&&<Menu/>} {section==='music'&&<Music draft={draft} save={save}/>} {section==='photos'&&<Photos/>} {section==='guests'&&<Guests draft={draft} save={save} organiser={organiser}/>} {section==='singles'&&<Singles/>} {section==='live'&&<Live names={names}/>}</div></>}
 </section></main>;
}
function Home({draft,names,base,events}:{draft:WeddingDraft,names:string,base:string,events:any[]}){const next=events[0];return <><header className={styles.hero}><div><small>WELCOME TO</small><h1>{draft.title||`${names}'s Wedding Weekend`}</h1><p>▣ {formatDateRange(draft.startDate,draft.endDate)} &nbsp; | &nbsp; ◇ {draft.city||'Location to be confirmed'}</p><blockquote>“Different families.<br/>Same beautiful story.”</blockquote></div><div className={styles.next}><small>NEXT UP</small><h2>{next?.name||'Your celebration'}</h2><p>{next?`${next.day} at ${next.start}`:'Add your first event'}</p><Link href={`${base}/schedule`}>View schedule →</Link></div></header><div className={styles.quick}><Link href={`${base}/schedule`}><b>◇</b><span>Wedding schedule<small>See what’s happening</small></span>→</Link><Link href={`${base}/travel`}><b>▤</b><span>Your coach<small>Travel & timings</small></span>→</Link><Link href={`${base}/guests`}><b>♧</b><span>Guest list<small>Meet everyone</small></span>→</Link><Link href={`${base}/menu`}><b>♨</b><span>Menus<small>Food & dietary info</small></span>→</Link></div><div className={styles.homeGrid}><section className={styles.card}><div className={styles.cardHead}><h2>Wedding Schedule</h2><Link href={`${base}/schedule`}>View all →</Link></div>{(draft.schedule??[]).slice(0,2).map(day=><div className={styles.day} key={day.id}><h3>{day.label} · {day.date}</h3>{day.events.slice(0,3).map(e=><div className={styles.event} key={e.id}><time>{e.start}</time><i>{e.type==='Food'?'♨':e.type==='Travel'?'▤':'✦'}</i><span><b>{e.name}</b><small>{e.description}</small></span><em>›</em></div>)}</div>)}</section><aside className={styles.right}><section className={styles.card}><h2>Announcements</h2><div className={styles.notice}>🎉 <span>Welcome to {names}'s wedding space.</span></div><div className={styles.notice}>ℹ️ <span>Live wedding updates will appear here.</span></div></section><section className={`${styles.card} ${styles.welcome}`}><h2>♡ We’re so happy you’re here!</h2><p>This is your private place for the whole celebration. Keep everyone informed, involved and together.</p><small>{names}</small></section></aside></div></>}
function Schedule({draft}:{draft:WeddingDraft}){return <div className={styles.stack}>{(draft.schedule??[]).map(day=><section className={styles.card} key={day.id}><div className={styles.eyebrow}>{day.label}</div><h2>{day.date}</h2>{day.events.map(e=><div className={styles.bigEvent} key={e.id}><div><strong>{e.start}</strong><small>{e.end}</small></div><i>{e.type==='Food'?'♨':e.type==='Travel'?'▤':'✦'}</i><span><h3>{e.name}</h3><p>{e.description}</p></span></div>)}</section>)}</div>}
function Events({events}:{events:any[]}){return <div className={styles.cards}>{events.map(e=><article className={styles.featureCard} key={e.id}><div className={styles.eyebrow}>{e.label} · {e.start}</div><h2>{e.name}</h2><p>{e.description||'Everything you need to know about this part of the celebration.'}</p><div className={styles.meta}>◇ {e.day} &nbsp; · &nbsp; {e.type}</div></article>)}</div>}
function Travel(){return <div className={styles.twoCol}><section className={styles.card}><div className={styles.eyebrow}>GETTING AROUND</div><h2>Wedding coaches</h2>{samples.travel.map(x=><div className={styles.infoRow} key={x[0]}><strong>{x[1]}</strong><span><h3>{x[0]}</h3><p>{x[2]} · {x[3]}</p></span></div>)}</section><section className={`${styles.card} ${styles.tint}`}><h2>Venue & directions</h2><div className={styles.map}>◇<span>Wedding venue map</span></div><p>Coach details, parking instructions, taxi numbers and venue directions all live here, away from the group-chat fog.</p></section></div>}
function Menu(){return <div className={styles.cards}>{samples.menu.map((x,i)=><article className={styles.featureCard} key={x[0]}><div className={styles.foodIcon}>♨</div><div className={styles.eyebrow}>MENU {i+1}</div><h2>{x[0]}</h2><h3>{x[1]}</h3><p>{x[2]}</p><button>Dietary information</button></article>)}</div>}
function Music({draft,save}:{draft:WeddingDraft,save:(p:Partial<WeddingDraft>)=>void}){const songs=draft.songs?.length?draft.songs:starterSongs;const [value,setValue]=useState('');const add=()=>{if(!value.trim())return;save({songs:[{id:`song-${Date.now()}`,song:value.trim(),likes:0},...songs]});setValue('')};return <div className={styles.twoCol}><section className={styles.card}><div className={styles.eyebrow}>THE SOUNDTRACK</div><h2>Request a song</h2><p>Heard something that absolutely has to make the dance floor? Add it to the wedding wish-list.</p><form onSubmit={e=>{e.preventDefault();add()}}><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Song · Artist"/><button>Add request ♫</button></form></section><section className={styles.card}><h2>Guest requests</h2>{songs.map(s=><div className={styles.song} key={s.id}><b>♫</b><span>{s.song}</span><button className={styles.likeButton} onClick={()=>save({songs:songs.map(x=>x.id===s.id?{...x,likes:x.likes+1}:x)})}>♡ {s.likes}</button></div>)}</section></div>}
function Photos(){return <><section className={styles.upload}><b>▧</b><h2>Share the weekend</h2><p>Guest photos will collect here in one private wedding album.</p><button>Add photos</button></section><div className={styles.photoGrid}>{['Haldi','Sangeet','Ceremony','Reception','Family','Dance floor'].map(x=><div key={x}><span>▧</span><small>{x}</small></div>)}</div></>}
function Guests({draft,save,organiser}:{draft:WeddingDraft,save:(p:Partial<WeddingDraft>)=>void,organiser:boolean}){const guests=draft.guests?.length?draft.guests:starterGuests;const add=()=>{const name=window.prompt('Guest name');if(!name?.trim())return;const group=window.prompt('Group / family','Friends')||'Friends';save({guests:[...guests,{id:`guest-${Date.now()}`,name:name.trim(),group,status:'Awaiting RSVP'}]})};return <section className={styles.card}><div className={styles.cardHead}><div><div className={styles.eyebrow}>THE PEOPLE</div><h2>{guests.length} guests</h2></div>{organiser&&<button onClick={add}>＋ Add guest</button>}</div>{guests.map(g=><div className={styles.guest} key={g.id}><div>{g.name[0]}</div><span><strong>{g.name}</strong><small>{g.group}</small></span><em>{g.status}</em>{organiser&&<button className={styles.removeButton} onClick={()=>save({guests:guests.filter(x=>x.id!==g.id)})}>Remove</button>}</div>)}</section>}
function Singles(){return <div className={styles.twoCol}><section className={`${styles.card} ${styles.romance}`}><div className={styles.heart}>♡</div><div className={styles.eyebrow}>OPTIONAL · PRIVATE · WEDDING-ONLY</div><h2>Meet someone at the wedding</h2><p>A tiny dating corner for single guests who choose to join. Profiles are only visible to other opted-in wedding guests and disappear after the celebration.</p><button>Join Singles</button></section><section className={styles.card}><h2>How it works</h2>{[['1','Opt in','Nothing is public unless you choose to join.'],['2','Make a tiny profile','A photo, name and a few prompts.'],['3','Match quietly','Only mutual likes open a conversation.']].map(x=><div className={styles.step} key={x[0]}><b>{x[0]}</b><span><h3>{x[1]}</h3><p>{x[2]}</p></span></div>)}</section></div>}
function Live({names}:{names:string}){const updates=[['18:42','Coach update','The first reception coach will leave from the main entrance at 15:30.'],['14:05','Photos','Family photographs will take place immediately after the ceremony.'],['09:10','Welcome!','The wedding weekend has officially begun. Have an amazing time!']];return <div className={styles.twoCol}><section className={styles.card}><div className={styles.liveHead}><span></span> LIVE</div><h2>Wedding updates</h2>{updates.map(u=><div className={styles.update} key={u[0]}><time>{u[0]}</time><span><strong>{u[1]}</strong><p>{u[2]}</p></span></div>)}</section><section className={`${styles.card} ${styles.tint}`}><div className={styles.eyebrow}>FROM THE ORGANISERS</div><h2>Everything important, right here.</h2><p>Last-minute timing changes, coach movements, weather notes and spontaneous “everyone to the dance floor” messages appear here.</p><blockquote>“See you on the dance floor.”</blockquote><small>{names}</small></section></div>}
