import {NextResponse} from 'next/server';
import {d1Query} from '../../../lib/d1';
import {GUEST_COOKIE,currentGuestSession,encodeGuestSession} from '../../../lib/guestSession';
import {invitationCode} from '../../../lib/weddingDraft';

type Wedding={id:string;slug:string;partner_one:string;partner_two:string;start_date:string|null};
type Guest={id:string;name:string};
export async function GET(){const session=await currentGuestSession();return NextResponse.json({ok:true,guest:session?{id:session.guestId,name:session.guestName,weddingSlug:session.weddingSlug}:null})}
export async function POST(request:Request){try{const{slug,name,code}=await request.json();const wedding=(await d1Query<Wedding>('SELECT id,slug,partner_one,partner_two,start_date FROM weddings WHERE slug=? LIMIT 1',[String(slug)]))[0];if(!wedding)return NextResponse.json({ok:false,error:'Wedding not found.'},{status:404});const expected=invitationCode({partnerOne:wedding.partner_one,partnerTwo:wedding.partner_two,startDate:wedding.start_date??'',endDate:'',city:'',title:'',traditions:[]});if(String(code||'').trim().toUpperCase()!==expected)return NextResponse.json({ok:false,error:'That invitation code does not match this wedding.'},{status:401});const guests=await d1Query<Guest>('SELECT id,name FROM guests WHERE wedding_id=? AND lower(trim(name))=lower(trim(?))',[wedding.id,String(name||'')]);if(guests.length!==1)return NextResponse.json({ok:false,error:guests.length?'Please ask the organiser to make guest names unique.':'We could not find that name on the guest list.'},{status:401});const expiresAt=Date.now()+1000*60*60*24*30;const response=NextResponse.json({ok:true,guest:guests[0]});response.cookies.set(GUEST_COOKIE,encodeGuestSession({weddingId:wedding.id,weddingSlug:wedding.slug,guestId:guests[0].id,guestName:guests[0].name,expiresAt}),{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/',maxAge:60*60*24*30});return response}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:'Could not join wedding.'},{status:500})}}
export async function DELETE(){const response=NextResponse.json({ok:true});response.cookies.set(GUEST_COOKIE,'',{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/',maxAge:0});return response}
