'use client';
import {FormEvent,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import styles from './page.module.scss';

export default function LandingPage(){
 const router=useRouter();const[open,setOpen]=useState(false);const[name,setName]=useState('');const[code,setCode]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 useEffect(()=>{const openJoin=()=>setOpen(true);window.addEventListener('milni:join-wedding',openJoin);return()=>window.removeEventListener('milni:join-wedding',openJoin)},[]);
 const join=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/guest-session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,code})});const x=await r.json();if(!r.ok)throw new Error(x.error||'Could not join wedding.');router.push(`/wedding/${x.weddingSlug}`)}catch(err){setError(err instanceof Error?err.message:'Could not join wedding.')}finally{setBusy(false)}};
 return <main className={styles.page}><nav className={styles.nav}><div className={styles.brand}><span className={styles.lotus}>♢</span><strong>MILNI</strong><small>PEOPLE · TRADITIONS · TOGETHER</small></div><div className={styles.navActions}><a href="/organiser">Organiser sign in</a><a href="/create">Create your wedding</a></div></nav><section className={styles.hero}><div className={styles.copy}><p className={styles.eyebrow}>YOUR WEDDING · IN ONE PLACE</p><h1>Different families.<br/>One beautiful story.</h1><p className={styles.intro}>Plan every event, keep every guest informed and bring everyone together in a private wedding space built around your traditions.</p><div className={styles.actions}><a className={styles.primary} href="/create">Start planning →</a><button type="button" className={styles.secondary} onClick={()=>setOpen(true)}>Join a wedding</button><a className={styles.organiserLink} href="/organiser">Organiser sign in</a></div></div><aside className={styles.card}><span>THE WEDDING WEEKEND</span><h2>Everything your guests need, without the group-chat archaeology.</h2><div className={styles.features}><p>Schedule & ceremonies</p><p>Travel & coaches</p><p>Live updates</p><p>Menus & dietary info</p><p>Song requests</p><p>Shared memories</p></div></aside></section>{open&&<div className={styles.joinOverlay} onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><form className={styles.joinModal} onSubmit={join}><button type="button" className={styles.joinClose} onClick={()=>setOpen(false)}>×</button><p className={styles.eyebrow}>JOIN A WEDDING</p><h2>Welcome to MILNI</h2><p>Enter your name exactly as it appears on the guest list and the invitation code shared by the couple.</p><label>Your full name<input autoFocus autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Aman Kapoor" required/></label><label>Invitation code<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Wedding code" required/></label>{error&&<div className={styles.joinError}>{error}</div>}<button className={styles.joinSubmit} disabled={busy||!name.trim()||!code.trim()}>{busy?'Finding your wedding…':'Join wedding →'}</button><small>Have a personal invitation link or QR? Open that instead for instant access.</small></form></div>}</main>;
}