import {NextResponse} from 'next/server';
import {d1Execute,d1Query} from '../../../../lib/d1';

type WeddingRow={id:string};
type ProfileRow={id:string;guest_id:string;name:string;age:number;pronouns:string|null;wedding_side:string|null;connection_to_couple:string|null;bio:string|null;interests:string|null;photo_object_key:string|null;opted_in:number};
const imageUrl=(key:string|null)=>key?`/api/media?key=${encodeURIComponent(key)}`:undefined;
const toProfile=(row:ProfileRow)=>({id:row.id,guestId:row.guest_id,name:row.name,age:row.age,pronouns:row.pronouns??undefined,side:row.connection_to_couple??row.wedding_side??'Friends',bio:row.bio??'',interests:row.interests?JSON.parse(row.interests):[],photoUrl:imageUrl(row.photo_object_key),optedIn:Boolean(row.opted_in)});
async function weddingId(slug:string){return (await d1Query<WeddingRow>('SELECT id FROM weddings WHERE slug=? LIMIT 1',[slug]))[0]?.id}
export async function GET(_request:Request,{params}:{params:Promise<{slug:string}>}){try{const{slug}=await params;const id=await weddingId(slug);if(!id)return NextResponse.json({ok:false,error:'Wedding not found'},{status:404});const rows=await d1Query<ProfileRow>('SELECT id,guest_id,name,age,pronouns,wedding_side,connection_to_couple,bio,interests,photo_object_key,opted_in FROM singles_profiles WHERE wedding_id=? AND opted_in=1 ORDER BY created_at',[id]);return NextResponse.json({ok:true,profiles:rows.map(toProfile)})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:'Singles load failed'},{status:500})}}
export async function POST(request:Request,{params}:{params:Promise<{slug:string}>}){try{const{slug}=await params;const id=await weddingId(slug);if(!id)return NextResponse.json({ok:false,error:'Wedding not found'},{status:404});const profile=await request.json();if(!profile.guestId||!profile.name?.trim()||Number(profile.age)<18)return NextResponse.json({ok:false,error:'Choose your guest identity and complete your profile.'},{status:400});const guest=await d1Query<{id:string}>('SELECT id FROM guests WHERE id=? AND wedding_id=? LIMIT 1',[String(profile.guestId),id]);if(!guest[0])return NextResponse.json({ok:false,error:'Guest not found for this wedding.'},{status:400});const photoKey=typeof profile.photoUrl==='string'&&profile.photoUrl.startsWith('/api/media?key=')?decodeURIComponent(profile.photoUrl.split('key=')[1]||''):null;await d1Execute(`INSERT INTO singles_profiles(id,wedding_id,guest_id,name,age,pronouns,wedding_side,connection_to_couple,bio,interests,photo_object_key,opted_in,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(wedding_id,guest_id) DO UPDATE SET name=excluded.name,age=excluded.age,pronouns=excluded.pronouns,wedding_side=excluded.wedding_side,connection_to_couple=excluded.connection_to_couple,bio=excluded.bio,interests=excluded.interests,photo_object_key=COALESCE(excluded.photo_object_key,singles_profiles.photo_object_key),opted_in=excluded.opted_in,updated_at=CURRENT_TIMESTAMP`,[`single-${String(profile.guestId)}`,id,String(profile.guestId),String(profile.name).trim(),Number(profile.age),profile.pronouns||null,profile.side||null,profile.side||null,profile.bio||'',JSON.stringify(profile.interests??[]),photoKey,profile.optedIn?1:0]);return NextResponse.json({ok:true})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:'Singles save failed'},{status:500})}}
